package com.codewalnut.ats.client;

/** Server-only storage adapter. Keys are generated by the app, never accepted from a browser. */
public interface PrivateDocumentStore {
    void put(String key, byte[] bytes, String sha256);
    byte[] get(String key);
}
