package com.codewalnut.ats.domain;

public enum AuditAction {
    LOGIN,
    LOGIN_REJECTED,
    USER_CREATED,
    USER_UPDATED,
    ACCESS_DENIED,
    CANDIDATE_ACCOUNT_CREATED,
    CANDIDATE_LOGIN,
    CANDIDATE_LOGIN_REJECTED,
    CLIENT_CREATED,
    JOB_CREATED,
    JOB_UPDATED,
    CANDIDATES_IMPORTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DOWNLOADED,
    CANDIDATE_APPLIED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CANCELLED,
    CANDIDATE_UPDATED
}
